### ISSUE TITLE
Previous process not killed when jau restarts

### ISSUE THREAD

**Issue by henrist** [Cantara/Java-Auto-Update#10]
Expected result:
- jau is running and has control of another process (process A)
- jau crashes/restarts but process A keeps running
- jau should terminate process A and run a new instance of the process it will control (process B)
- only process B should run (along jau)

Actual result:
- both process A and process B runs (process A not terminated)

**Comment by sherriff** [comment]
Not relevant anymore as the teste was performed on old code. All scenarios should be retested as part of #9
