### ISSUE TITLE
Get environment info and send as part of registerClient and checkForUpdate

### ISSUE THREAD

**Issue by sherriff** [Cantara/Java-Auto-Update#11]
Find useful data that can be extracted from the client environment and add to the envInfo map sent in registerClient and checkForUpdate. 

CPU, mem and disk usage is perhaps useful?

**Comment by sherriff** [comment]
Perhaps https://support.hyperic.com/display/SIGAR/Home is useful?

**Comment by totto** [comment]
isn't this completed @sherriff ?

**Comment by sindremehus** [comment]
An alternative method for remote monitoring of heap, thread and file description usage of (AWS) applications is to enable metrics in the AWS SDK:

https://aws.amazon.com/blogs/developer/enabling-metrics-with-the-aws-sdk-for-java/

**Comment by sindremehus** [comment]
To enable this in an AWS agent app:

1. Add this to "startServiceScript" in the JSON configuration:
```
-Dcom.amazonaws.sdk.enableDefaultMetrics=hostMetricName=my-agent,cloudwatchRegion=eu-west-1
```

2. Add this dependency to the agent:
```
<dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-java-sdk-cloudwatchmetrics</artifactId>
    <scope>runtime</scope>
</dependency>
```

3. Add this to logback.xml:
```
<logger name="com.amazonaws.latency" level="WARN"/>
<logger name="com.amazonaws.metrics.internal.cloudwatch.PredefinedMetricTransformer" level="ERROR"/>
```
