### ISSUE TITLE
Retries in registerClient

### ISSUE THREAD

**Issue by sherriff** [Cantara/Java-Auto-Update#12]
1. Add retries for registerClient according to https://wiki.cantara.no/display/dev/ClientConfigResource+endpoint. 

2. checkForUpdates: for now, let's assume that the updateInterval is set small enough that the regular update interval loop can serve as retry. 

Ensure it is easy to understand what's happening. For expected situations, do not include the stacktrace, but explain in the log statement what's happening. 

E.g. 
Connection refused to ConfigService url=urlHere. Retrying in xx seconds. 
Internal server error in ConfigService url=urlHere. Retrying in xx seconds.

**Comment by jorunfa** [comment]
Retries for registerClient is implemented. checkForUpdates wasn't changed.
