### ISSUE TITLE
Support clientName and tags configuration

### ISSUE THREAD

**Issue by sherriff** [Cantara/Java-Auto-Update#16]
Need some sort of property which can be set in JAU properties which ConfigService can use to select specific configuration for an instance of an application. 

Provided by JAU
artifactId: name of application (mandatory)
clientName: some name to be used in CS  (optional)
tags: comma separated string of tags to be used (e.g. HA) (optional)

Assigned by ConfigService:
clientId: uuid

**Comment by jorunfa** [comment]
clientName from properties implemented in 5d50717e9e . Tags not implemented yet.

**Comment by jorunfa** [comment]
Both clientName and tags are now supported.
