### ISSUE TITLE
Support setting environment variables for forked process

### ISSUE THREAD

**Issue by sindremehus** [Cantara/Java-Auto-Update#17]
Use case: My app needs some configuration (AWS credentials) that we don't wanna provide through ConfigService.  The configuration should be part of the zip assembly and end up as a local property file.

I'm planning to implement support for this as follows:

1. Add a file config_override/env.properties.  Empty by default.
2. When forking the process, make all properties in env.properties available as environment variables for the new process.

**Comment by sherriff** [comment]
Is it a good idea to agree on naming conventions for the properties-files for JAU and the application? 
E.g. use "jau" and "application" as part of the filename?

**Comment by sindremehus** [comment]
Agreed.  I suggest:

jau.properties
application-env.properties

**Comment by sherriff** [comment]
Looks good. And both files resides in a "config_override" folder so that information is captured there...?

**Comment by sindremehus** [comment]
Yup

**Comment by StigLau** [comment]
Not sure if http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/credentials.html is applicable for this use case, but  ~/.aws/credentials is ok if using sdk classes
