### ISSUE TITLE
Simplify packaging of JAU apps

### ISSUE THREAD

**Issue by sindremehus** [Cantara/Java-Auto-Update#18]
Use case: I want to create a ready-to-ship zip file for a JAU app. The values in config.properties (and env.properties) should be set correctly.

What is the easiest way to accomplish this?

So far I have solved it by creating a small maven project which:

1. Declares java-auto-update.zip as a dependency.
2. Unzips java-auto-update.zip
3. Overwrites config.properties and env.properties with application-specific content.
4. Re-zips it (using maven assembly)

Is there a better way?

**Comment by andeero** [comment]
Filtering when building might be a possibility. Will look into.

**Comment by andeero** [comment]
Solution found is good enough. Closing.
