### ISSUE TITLE
Ensure any existing managed process is killed before starting new 

### ISSUE THREAD

**Issue by sherriff** [Cantara/Java-Auto-Update#4]

**Comment by kjarnet** [comment]
Kill gracefully (allow it to finish important work), or force-kill if waiting too long.

**Comment by kjarnet** [comment]
Depends on GH-7, as without a periodic check, the updater only starts a new process on startup.

**Comment by kjarnet** [comment]
Needs more manual testing as well as unit-tests.
Should probably be made more robust, and we might need to add monitoring of the running process as well - now the app is only restarted once each updateinterval, _and only if there has been changes to the config_.
