### ISSUE TITLE
Make registerClient and checkForUpdate production ready

### ISSUE THREAD

**Issue by sherriff** [Cantara/Java-Auto-Update#9]
1. Identify important scenarios to support. 
2. Starting testing each scenario and try to write automatic tests. 

Two axis to support: 
a. Functional https://wiki.cantara.no/display/dev/ClientConfigResource+endpoint
b. Process management: https://wiki.cantara.no/display/dev/JAU+process+management

**Comment by totto** [comment]
should this be closed too, @sherriff ?
